name: Bash CI/CD Test

on: 
  push:
    branches:
      - "main"
      - "master"
  pull_request:
    branches:
      - "main"
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    
    - name: Bash Betigini Calistir
      run: |
        chmod +x kontrol.sh
        ./kontrol.sh

    - name: Ek kod kalitesi kontrolu (ShellCheck)
      uses: ludeeus/action-shellcheck@2.0.0
      with:
        check_together: 'yes'
  
  deploy: 
    needs: build 
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Sürüm veya Dagitim Adimi
        run: |
          echo "Testler ve kalite kontrolleri basariyla gecti!"
          echo "Kod canli ortama veya GitHub Release alanina aktariliyor..."
