name: Bash CI Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    
    - name: Bash Betigini Calistir
      run: |
        chmod +x kontrol.sh
        ./kontrol.sh